language: go

sudo: false

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

before_install:
  - go get github.com/golang/lint/golint

before_script:
  - go vet ./...
  - golint -set_exit_status ./...

script:
  - go test -v ./...
